CRITICAL - 2023-03-10 07:24:55 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 224.
 1 SYSTEMPATH\CodeIgniter.php(224): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(182): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 ROOTPATH\spark(83): CodeIgniter\CodeIgniter->initialize()
ERROR - 2023-03-10 00:27:16 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'dashboard' in D:\xampp\htdocs\aplic-dashboard\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\xampp\htdocs\aplic-dashboard\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'dashboard', 3306, '', 0)
#1 D:\xampp\htdocs\aplic-dashboard\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\aplic-dashboard\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\aplic-dashboard\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\aplic-dashboard\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\aplic-dashboard\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 D:\xampp\htdocs\aplic-dashboard\app\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
#7 D:\xampp\htdocs\aplic-dashboard\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\aplic-dashboard\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\aplic-dashboard\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\aplic-dashboard\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\aplic-dashboard\system\Commands\Server\rewrite.php(46): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'dashboard' in D:\xampp\htdocs\aplic-dashboard\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\xampp\htdocs\aplic-dashboard\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\aplic-dashboard\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\aplic-dashboard\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\aplic-dashboard\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\aplic-dashboard\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 D:\xampp\htdocs\aplic-dashboard\app\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
#6 D:\xampp\htdocs\aplic-dashboard\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#7 D:\xampp\htdocs\aplic-dashboard\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 D:\xampp\htdocs\aplic-dashboard\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\aplic-dashboard\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\aplic-dashboard\system\Commands\Server\rewrite.php(46): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-10 00:27:16 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'dashboard'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `user_name` = :user_name:
AND `user_password` = :user_password:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-03-10 00:29:17 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'dashboard' in D:\xampp\htdocs\aplic-dashboard\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\xampp\htdocs\aplic-dashboard\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'dashboard', 3306, '', 0)
#1 D:\xampp\htdocs\aplic-dashboard\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\aplic-dashboard\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\aplic-dashboard\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\aplic-dashboard\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\aplic-dashboard\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 D:\xampp\htdocs\aplic-dashboard\app\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
#7 D:\xampp\htdocs\aplic-dashboard\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\aplic-dashboard\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\aplic-dashboard\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\aplic-dashboard\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\aplic-dashboard\system\Commands\Server\rewrite.php(46): require_once('D:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'dashboard' in D:\xampp\htdocs\aplic-dashboard\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\xampp\htdocs\aplic-dashboard\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\aplic-dashboard\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\aplic-dashboard\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\aplic-dashboard\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\aplic-dashboard\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 D:\xampp\htdocs\aplic-dashboard\app\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
#6 D:\xampp\htdocs\aplic-dashboard\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#7 D:\xampp\htdocs\aplic-dashboard\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 D:\xampp\htdocs\aplic-dashboard\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\aplic-dashboard\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\aplic-dashboard\system\Commands\Server\rewrite.php(46): require_once('D:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-10 00:29:17 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'dashboard'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `user_name` = :user_name:
AND `user_password` = :user_password:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-10 00:32:54 --> Invalid file: user.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('user', [], true)
 3 APPPATH\Controllers\User.php(30): view('user', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-10 00:33:12 --> Invalid file: user.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('user', [], true)
 3 APPPATH\Controllers\User.php(30): view('user', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-10 00:34:47 --> Invalid file: user.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('user', [], true)
 3 APPPATH\Controllers\User.php(30): view('user', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-10 00:35:47 --> syntax error, unexpected token "===", expecting "function" or "const"
in APPPATH\Models\MenuModel.php on line 23.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Models\\MenuModel.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\MenuModel')
 3 APPPATH\Controllers\Menu.php(18): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\MenuModel')
 4 SYSTEMPATH\CodeIgniter.php(889): App\Controllers\Menu->__construct()
 5 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
