ERROR - 2023-02-25 01:36:24 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'dashboard', 3306, '', 0)
#1 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\app\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
#7 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\XAMPP\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\app\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
#6 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#7 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\XAMPP\\htdocs...')
#11 {main}
CRITICAL - 2023-02-25 01:36:24 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `user_name` = :user_name:
AND `user_password` = :user_password:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-25 01:37:05 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'dashboard', 3306, '', 0)
#1 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\app\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
#7 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\XAMPP\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\app\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
#6 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#7 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\XAMPP\htdocs\aplic-dashboard\aplic-dashboard-ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\XAMPP\\htdocs...')
#11 {main}
CRITICAL - 2023-02-25 01:37:05 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `user_name` = :user_name:
AND `user_password` = :user_password:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
